name: aws_s3_client_extensions_to_serverpod
description: Additional REST API calls to AWS S3 not implemented by Serverpod
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  lints: ^2.0.1
  test: ^1.21.0
dependencies:
  amazon_cognito_identity_dart_2: ">=1.0.3 <3.3.0"
  http: ">=0.13.5 <2.0.0"
  xml2json: ">=5.3.6 <7.0.0"
  serverpod: ^1.1.1
  json_annotation: ^4.8.1
